#Path for the Default Space configurations directory
aalSpaceConfigurationPath=target/rundir/configadmin
#Path to the Space XSD file
aalSpaceSchemaURL= target/rundir/configadmin
aalSpaceSchemaName= space.xsd
#Millis to wait after the request to leave before closing the channels
waitBeforeClosingChannels = 2000
waitAfterJoinRequest = 3000

#Properties for the peer
peerRole=COORDINATOR

#Properties for Space Manager
spaceExtension=space

#Validate Space XML files before using them
aalSpaceValidation = false

#Seconds for the space validity. -1 endless. Value must be natural and > 1
#7200 s -> 2 ore
aalSpaceLifeTime = 3

